language: c

before_script:
  - git clone https://github.com/RT-Thread/rt-thread
  - mkdir ~/toolchain
  - curl -s https://sourcery.mentor.com/public/gnu_toolchain/arm-none-eabi/arm-2011.03-42-arm-none-eabi-i686-pc-linux-gnu.tar.bz2 | tar xjf - -C ~/toolchain

before_script:
  - export RTT_EXEC_PATH=~/toolchain/arm-2011.03/bin
  - cd rt-thread
  - export RTT_ROOT=`pwd`
  - cd bsp/jz47xx

script:
  - scons

notifications:
  email: false

env:
  - RTT_CC='gcc'
