language: c

install:
  - mkdir ~/toolchain
  - curl -s https://sourcery.mentor.com/public/gnu_toolchain/mips-sde-elf/mips-2011.09-86-mips-sde-elf-i686-pc-linux-gnu.tar.bz2 | tar xjf - -C ~/toolchain

before_script:
  - export RTT_EXEC_PATH=~/toolchain/mips-2011.09/bin
  - git clone https://github.com/RT-Thread/rt-thread.git
  - cd rt-thread
  - export RTT_ROOT=`pwd`
  - cd bsp/jz47xx

script:
  - scons

notifications:
  email: false

env:
  - RTT_CC='gcc'
